apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
        - name: apache-php
          image: {{ .Values.apachePhp.image }}
          ports:
            - containerPort: {{ .Values.apachePhp.port }}
