apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  type: {{ .Values.mysql.type }}
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - port: 3306
      targetPort: {{ .Values.mysql.port }}
