apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: {{ .Values.phpmyadmin.name }}
    spec:
      containers:
        - name: {{ .Values.phpmyadmin.name }}
          image: {{ .Values.phpmyadmin.image }}
          env:
            - name: PMA_HOST
              value: {{ .Values.mysql.name }}
          ports:
            - containerPort: {{ .Values.phpmyadmin.port }}
