apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phpmyadmin.name }}
spec:
  type: {{ .Values.phpmyadmin.type }}
  selector:
    app: {{ .Values.phpmyadmin.name }}
  ports:
    - port: {{ .Values.phpmyadmin.port }}
      targetPort: {{ .Values.phpmyadmin.port }}
      nodePort: {{ .Values.phpmyadmin.nodePort }}
