replicaCount: 1

image:
  repository: kasoro/devops
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 8080

mysql:
  host: "mysql"
  database: "mysql"
  user: "user"
  password: "root"